PREFIX saltmfg: <https://example.org/ontology/salt/manufacturing/v1.0#>

SELECT ?resource ?source ?target
WHERE {
  ?resource a saltmfg:KnowledgeBase .
  ?resource a saltmfg:ManufacturingResource .
  ?resource a saltmfg:MaterialRequirement .
  ?resource a saltmfg:WorkOrder .
  ?source saltmfg:requiresMaterial ?target .
}
