/**
 * Domain configuration for Financial Services
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "financial-services",
  name: "Financial Services",
  description: "Investment management, trading, compliance, and risk assessment",
  tagline: "AI-powered Financial Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"Account": "#0ea5e9", "Decision": "#8b5cf6", "Event": "#f97316", "Location": "#a855f7", "Object": "#eab308", "Organization": "#3b82f6", "Person": "#22c55e", "Policy": "#dc2626", "Security": "#06b6d4", "Transaction": "#f59e0b"};

export const NODE_SIZES: Record<string, number> = {"Account": 20, "Decision": 25, "Event": 20, "Location": 20, "Object": 20, "Organization": 30, "Person": 25, "Policy": 20, "Security": 20, "Transaction": 15};

export const DEFAULT_CYPHER = `MATCH (p:Person)-[r]-(n) RETURN p, r, n LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Portfolio Analysis", "prompts": ["Show me a summary of all client accounts and their current balances", "What are the recent transactions for the Smith family trust?", "Which portfolios have the highest risk exposure?"]}, {"name": "Compliance \u0026 Risk", "prompts": ["Are there any accounts flagged for compliance review?", "Show me all trades that exceeded position limits this quarter", "What policies apply to international wire transfers?"]}, {"name": "Decision Intelligence", "prompts": ["What was the reasoning behind the decision to sell AAPL last week?", "Find similar past decisions to a proposed large bond allocation", "Show me the causal chain for the Smith portfolio rebalance"]}];
