/**
 * Domain configuration for Manufacturing
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "manufacturing",
  name: "Manufacturing",
  description: "Production management, quality control, supply chain, and equipment maintenance",
  tagline: "AI-powered Manufacturing Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"BillOfMaterials": "#a16207", "BusinessConcept": "#be123c", "CDSField": "#2563eb", "CDSView": "#0f766e", "Event": "#f97316", "Location": "#a855f7", "Machine": "#475569", "MaterialRequirement": "#0369a1", "Object": "#eab308", "Organization": "#3b82f6", "Part": "#0284c7", "Person": "#22c55e", "ProductionEvent": "#be123c", "ProductionLine": "#059669", "QualityReport": "#dc2626", "SalesDocument": "#c2410c", "ScheduleSlot": "#7e22ce", "SourceDataset": "#4f46e5", "Supplier": "#7c3aed", "SupplyCommitment": "#b45309", "TaxonomyConcept": "#a16207", "WorkCenter": "#0f766e", "WorkOrder": "#d97706"};

export const NODE_SIZES: Record<string, number> = {"BillOfMaterials": 20, "BusinessConcept": 20, "CDSField": 20, "CDSView": 20, "Event": 20, "Location": 20, "Machine": 25, "MaterialRequirement": 20, "Object": 20, "Organization": 25, "Part": 20, "Person": 20, "ProductionEvent": 20, "ProductionLine": 30, "QualityReport": 15, "SalesDocument": 20, "ScheduleSlot": 20, "SourceDataset": 20, "Supplier": 25, "SupplyCommitment": 20, "TaxonomyConcept": 20, "WorkCenter": 20, "WorkOrder": 20};

export const DEFAULT_CYPHER = `MATCH (wo:WorkOrder)-[r]-(n) RETURN wo, r, n LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Production Management", "prompts": ["Show me all active work orders sorted by priority", "What is the current capacity utilization of each production line?", "Which work orders are at risk of missing their due dates?"]}, {"name": "Quality \u0026 Compliance", "prompts": ["Show me the defect rate trend for the past quarter", "Which parts have the highest failure rates in quality inspection?", "Find all quality reports linked to supplier Acme Components"]}, {"name": "Supply Chain", "prompts": ["Which parts are below minimum stock levels?", "Compare lead times and quality ratings across our approved suppliers", "What is the bill of materials for part P-4500?"]}];
